/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rosha
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        applyStyles();
        pack(); // Automatically set the size based on the content
        setLocationRelativeTo(null); // Center the window on the screen
    }

    private void applyStyles() {
        // Style the panel
        UIStyle.stylePanel(jPanel1);

        // Style buttons
        UIStyle.styleButton(jButton1);
        UIStyle.styleButton(jButton2);

        // Style labels
        jLabel1.setFont(UIStyle.LABEL_FONT);
        jLabel2.setFont(UIStyle.LABEL_FONT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Customer ID");

        jButton1.setText("Login");
        jButton1.addActionListener(evt -> jButton1ActionPerformed(evt));

        jLabel2.setText("Don't have an account?");

        jButton2.setText("Register Now");
        jButton2.addActionListener(evt -> jButton2ActionPerformed(evt));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String enteredId = jTextField1.getText().trim();
        boolean found = false;

        try {
            // Check customer.txt
            java.io.BufferedReader reader = new java.io.BufferedReader(new java.io.FileReader("customer.txt"));
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(":");
                if (parts.length > 0 && parts[0].equalsIgnoreCase(enteredId)) {
                    found = true;
                    javax.swing.JOptionPane.showMessageDialog(this, "Access Granted: Customer (" + enteredId + ")");
                    CustomerMenu cm = new CustomerMenu();
                    cm.setCustomerId(enteredId);
                    cm.setVisible(true);
                    this.dispose(); // Close the login window
                    break;
                }
            }
            reader.close();

            if (!found) {
                // Check admin.txt
                reader = new java.io.BufferedReader(new java.io.FileReader("admin.txt"));
                while ((line = reader.readLine()) != null) {
                    String[] parts = line.split(":");
                    if (parts.length > 0 && parts[0].equals(enteredId)) {
                        found = true;
                        javax.swing.JOptionPane.showMessageDialog(this, "Access Granted: Admin (" + enteredId + ")");
                        AdminMenu cm = new AdminMenu();
                        cm.setVisible(true);
                        this.dispose(); // Close the login window
                        break;
                    }
                }
                reader.close();
            }

            if (!found) {
                // Check cashier.txt
                reader = new java.io.BufferedReader(new java.io.FileReader("cashier.txt"));
                while ((line = reader.readLine()) != null) {
                    String[] parts = line.split(":");
                    if (parts.length > 0 && parts[0].equals(enteredId)) {
                        found = true;
                        javax.swing.JOptionPane.showMessageDialog(this, "Access Granted: Cashier (" + enteredId + ")");
                        CashierMenu cm = new CashierMenu();
                        cm.setCshID(enteredId);
                        cm.setVisible(true);
                        this.dispose(); // Close the login window
                        break;
                    }
                }
                reader.close();
            }

            if (!found) {
                // Check mechanics.txt
                java.io.File mechanicFile = new java.io.File("mechanics.txt"); // Ensure the correct file name is used
                if (mechanicFile.exists()) {
                    reader = new java.io.BufferedReader(new java.io.FileReader(mechanicFile));
                    while ((line = reader.readLine()) != null) {
                        String[] parts = line.split(":");
                        if (parts.length > 0 && parts[0].equalsIgnoreCase(enteredId)) {
                            found = true;
                            javax.swing.JOptionPane.showMessageDialog(this, "Access Granted: Mechanic (" + enteredId + ")");
                            MechViewAppointments cm = new MechViewAppointments();
                            cm.setMechanicId(enteredId); // Pass the mechanic ID to filter appointments
                            //cm.setMechanicId(enteredId);
                            cm.setVisible(true);

                            this.dispose(); // Close the login window
                            break;
                        }
                    }
                    reader.close();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Mechanic file not found.");
                }
            }

            if (!found) {
                javax.swing.JOptionPane.showMessageDialog(this, "ID not found");
            }

        } catch (java.io.IOException ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error reading files.");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CreateAccount ca = new CreateAccount();
        ca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
